### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Gilnaa** [mu-editor/crash-reports#129]
[mu.log](https://github.com/mu-editor/mu/files/7015599/mu.log)

Version: 1.1.0.beta.5
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
s(zipped_wheels_filepath)
  File "C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Gilad Naaman\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Gilad Naaman\AppData\Local\python\mu\mu_venv-38-20210819-175625\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\GILADN~1\AppData\Local\Temp\tmp59dc_f5p\backcall-0.2.0-py2.py3-none-any.whl'

```

**Comment by carlosperate** [comment]
Hi @Gilnaa 

Thank you again for all your help testing this! In this end it look like it might be an bug in Python, so it's taken us a while to track it down. More info can be found in https://github.com/mu-editor/mu/issues/1926#issuecomment-1050168363

Would you be able to check if this version of Mu works in your environment?
That'd be really useful to us, to confirm everything is working correctly, and the fix doesn't break anything else.

The installer can be downloaded the bottom of this page, it's the middle file named `mu-editor-Windows-ab489a0c09e29a55bb7a158f380a10789eb6e2d5` (you need to be logged into GitHub for the download link to work):
https://github.com/mu-editor/mu/actions/runs/2444128277
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/4189262/172206615-b77d1013-9e1b-41a0-ba8d-da5cc0702d8d.png">

Thank you again!

**Comment by Gilnaa** [comment]
I've got some bad news
![image](https://user-images.githubusercontent.com/1339859/172940652-3516a548-076c-446b-ba4d-8e06936124c8.png)

**Comment by Gilnaa** [comment]
I've also got some good news (?)
![image](https://user-images.githubusercontent.com/1339859/172940731-f2c78ed3-f6e6-413c-9559-3cee6b058a81.png)


Seem to have opened just after the error reporter.
I'm confused, but overall it looks like it solved the issue partially.

**Comment by Gilnaa** [comment]
Welp, due to my ignorance, I'm going to assume that the initial failure is due to the old version from a year ago still being installed.
Looks like the installer works now, thank you very much :)

**Comment by carlosperate** [comment]
That was a weird crash report if the app the opened after, but if it is working now I think I'll count it as resolved 😄 
Thanks again for all the testing and confirming the latest fix seems to work! 👍

**Comment by lmatter** [comment]
@carlosperate , I'm brand new to CircuitPython (but not new to coding).  I too sadly have a username with a space in it - the new version of the installer worked.  This may be obvious, but it looks like that does not include the bundle.  Anyone else that runs into this probably also needs to install the bundle to run the sample programs in the tutorial (e.g., "ImportError: no module named 'neopixel'" happened to me)
