### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nickoslice4** [mu-editor/crash-reports#130]
I am entirely new to coding. I am following steps in "automate the boring stuff with Python" and was encouraged to download this.  Upon downloading, when I try to open Mu this is what happens.

[mu.log](https://github.com/mu-editor/mu/files/7228893/mu.log)

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
ed_wheels_filepath)
  File "C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Nick Ferraro\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Nick Ferraro\AppData\Local\python\mu\mu_venv-38-20210924-193448\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index "C:\Users\Nick Ferraro\AppData\Local\Temp\tmpfjr0m7ts\backcall-0.2.0-py2.py3-none-any.whl"'

```

**Comment by carlosperate** [comment]
Hi @nickoslice4 

We think we've got a fix for this issue. Would you be able to check if this version of Mu works for you?
If you could test this it would be really useful to us, to confirm everything is working correctly before we release it.

The installer can be downloaded the bottom of this page, it's the middle file named `mu-editor-Windows-ab489a0c09e29a55bb7a158f380a10789eb6e2d5` (you need to be logged into GitHub for the download link to work):
https://github.com/mu-editor/mu/actions/runs/2444128277
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/4189262/172206615-b77d1013-9e1b-41a0-ba8d-da5cc0702d8d.png">

Thank you!

**Comment by carlosperate** [comment]
Thanks for the report @nickoslice4 ! 

The new Mu Editor v1.2.0 release today fixes this issue, if you install the latest release for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be happy to look into that issue 👍

Thanks again!
