### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jomixl** [mu-editor/crash-reports#195]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: de_DE
Platform: Windows 10 10.0.19044 AMD64

```
Traceback (most recent call last):
  File "C:\Users\h81\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 760, in on_ls_fail
    self.disable()
  File "C:\Users\h81\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```

**Comment by jomixl** [comment]
[mu.log](https://github.com/mu-editor/crash-reports/files/8947255/mu.log)

**Comment by carlosperate** [comment]
Hi @jomixl,

Would you be able to try the windows installer from this page? https://github.com/mu-editor/mu/actions/runs/2299649753

You can download it from the Artifacts section (make sure you are logged in GitHub for the download link to work):
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/4189262/167603389-d6c58f69-c45f-4c4f-a817-769736bb5483.png">

I think the updates in that test installer could resolve the issue you might have with the last release. It would be really useful for us if you  could test it, thanks!

**Comment by carlosperate** [comment]
Hi @jomixl, were you able to try the test installer from my last message?

**Comment by carlosperate** [comment]
Thanks for the report @jomixl !

The new Mu Editor v1.2.0 released yesterday fixes this issue, if you download the latest installer for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be able to look into that issue 👍

Thanks again!
