### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Vickie2891** [mu-editor/crash-reports#200]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_DE
Platform: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64

```
ate
    self.install_baseline_packages()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 885, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 860, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 270, in install
    return self.run(
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 1:
ERROR: numpy-1.22.2-cp38-cp38-macosx_10_14_x86_64.whl is not a supported wheel on this platform.

```

**Comment by carlosperate** [comment]
Hi @Vickie2891, thank you for the report!

I believe you are hitting this issue: https://github.com/mu-editor/mu/issues/2120

Until we release a version of Mu with a fix this is a possible workaround:

Run the following command on a terminal:

```
rm /Applications/Mu\ Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/wheels/1.1.1.zip
```

Then launch Mu again.

If you could let us know if this worked or not that would help us a lot as well. Thanks!

**Comment by Vickie2891** [comment]
Hi there,Wow, it works !Thanks a lot !@***@***.*** Wu------------------ Original ------------------From: Carlos Pereira Atencio  ***@***.***>Date: Fri, Jun 24, 2022 4:49 PMTo: mu-editor/crash-reports ***@***.***>Cc: Vickie2891 ***@***.***>, Mention ***@***.***>Subject: Re: [mu-editor/crash-reports] Crash Report (Issue #200)
Hi @Vickie2891, thank you for the report!
I believe you are hitting this issue: mu-editor/mu#2120
Until we release a version of Mu with a fix this is a possible workaround:
Run the following command on a terminal:
rm /Applications/Mu\ Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/wheels/1.1.1.zip

Then launch Mu again.
If you could let us know if this worked or not that would help us a lot as well. Thanks!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/mu-editor/crash-reports/issues/200#issuecomment-1165650868",
"url": "https://github.com/mu-editor/crash-reports/issues/200#issuecomment-1165650868",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by carlosperate** [comment]
I'm glad that worked, thanks for the update!
I'll close this crash report as we are already tracking the problem in issue https://github.com/mu-editor/mu/issues/2120.
