### ISSUE TITLE
learn python

### ISSUE THREAD

**Issue by amineskak** [mu-editor/crash-reports#321]
i ve been without work for several months now, so I decide to go freelance, even doing my own project, and I want to learn coding, knowing that I've been a student in that domain, and I find it pretty hard to start alone, so if there's out there anyone interested in sharing some information with me, please let's get in touch. 
Thank u

**Comment by carlosperate** [comment]
Hi @amineskak,

This repository is used only to raise Crash Reports from the Mu Editor, so there is very few people reading this issues.

There is a Python Discord community that is very friendly to begginers, and you'll probably find it more helpful: https://www.pythondiscord.com

Best of luck in your Python adventure!
