### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by drgouda** [mu-editor/crash-reports#342]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: de_DE
Platform: Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 760, in on_ls_fail
    self.disable()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```
[mu.log](https://github.com/mu-editor/crash-reports/files/9936763/mu.log)

**Comment by carlosperate** [comment]
Thanks for the report @drgouda !

The new Mu Editor v1.2.0 released yesterday fixes this issue, if you download the latest installer for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be able to look into that issue 👍

Thanks again!
