### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SufjanK** [mu-editor/crash-reports#545]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.22621 AMD64

```
sufjan\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\main.py", line

```

**Comment by carlosperate** [comment]
I'll close this one as a duplicate of https://github.com/mu-editor/crash-reports/issues/544 and we can continue the debugging over there 👍
