### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by profjr** [mu-editor/crash-reports#655]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: pt_BR
Platform: Linux 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64

```
Traceback (most recent call last):
  File "/home/aluno/.local/lib/python3.8/site-packages/mu/app.py", line 160, in run
    raise ex
  File "/home/aluno/.local/lib/python3.8/site-packages/mu/app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "/home/aluno/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "/home/aluno/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 827, in create
    self.create_venv()
  File "/home/aluno/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/aluno/.local/share/mu/mu_venv-38-20240514-112723
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by profjr** [comment]
After running the full update of my Linux Mint, the mu-editor stopped working. I uninstalled and installed again, using several methods, but I was unsuccessful. Please, could you help me? Thanks.

**Comment by carlosperate** [comment]
Hi @profjr,

How did you install Mu?

Looks like the virtualenv module is missing from the OS package manager, are you able to run this command succesfully?
```
python3 -m virtualenv --version
```

**Comment by profjr** [comment]
Friend, the virtualenv was not installed.  I installed it and now the
mu-editor is working. Thanks.

Em ter., 14 de mai. de 2024, 15:40, Carlos Pereira Atencio <
***@***.***> escreveu:

**Comment by carlosperate** [comment]
Awesome, glad that worked!

**Comment by profjr** [comment]
Well, my friend, in fact, it didn't work, it stays on that initial screen
when it is run for the first time and there is a message stating that the
first time it may take a while to run.  Today I'm no longer at school, I'll
only be there on Friday, to test again and give you new feedback.  Anyway,
I appreciate your help so far.  I hope I can collaborate, as other users
may have the same problem.

Em ter., 14 de mai. de 2024, 20:15, Carlos Pereira Atencio <
***@***.***> escreveu:

**Comment by carlosperate** [comment]
Oh, I'm sorry you are still experiencing issues. That initial start up might take a while, but hopefully it will succed eventually. If it instead fails, it should open a new browser window to report a new problem, so if you could create a new GH issue with that info it would be great. Thanks!
